name = "Surreal Query Language"
grammar = "surrealql"
path_suffixes = ["surql"]
line_comments = ["-- "]
autoclose_before = ":\"'}]>"
brackets = [
    { start = "<", end = ">", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "'", end = "'", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = true },
    #     { start = "!--", end = " --", close = true, newline = true },
    #     { start = "\"", end = "\"", close = true, newline = true, not_in = ["string"] },
    #     { start = "`", end = "`", close = true, newline = true, not_in = ["string"] },
]
